<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'value' => 'E-Commerce Store',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Site Name',
                'description' => 'The official name of the website. Displayed in the site header and browser title bar.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'site_description',
                'value' => 'Your one-stop shop for quality products',
                'type' => 'textarea',
                'group' => 'general',
                'label' => 'Site Description',
                'description' => 'A short description of the website. Used for SEO and when sharing links on social media.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'address',
                'value' => 'EGYPT, Alexandria, al-Ajami',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Address',
                'description' => 'The physical address of the store location.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'business_hours',
                'value' => 'Mon-Fri: 9am-5pm',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Business Hours',
                'description' => 'The official working hours of the store.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'orders_via_whatsapp_only',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Orders via WhatsApp Only',
                'description' => 'If enabled, customers cannot place orders on the website. They must order via WhatsApp only.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 6,
            ],

            // Contact Settings
            [
                'key' => 'contact_email',
                'value' => 'contact@example.com',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Contact Email',
                'description' => 'Main email address for customer inquiries and support.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+1 (234) 567-8900',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Contact Phone',
                'description' => 'Main phone number for customer inquiries and support.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'whatsapp_number',
                'value' => '201503410324',
                'type' => 'text',
                'group' => 'whatsApp',
                'label' => 'WhatsApp Number',
                'description' => 'WhatsApp number in international format starting with country code. Example: 201503400000 (without + or 00).',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'whatsapp_welcome_message',
                'value' => 'Welcome to our store! We are happy to serve you.',
                'type' => 'textarea',
                'group' => 'whatsApp',
                'label' => 'WhatsApp Welcome Message',
                'description' => 'This is the first message customers receive when contacting the store via WhatsApp.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'whatsapp_product_message',
                'value' => 'أرغب في طلب هذا المنتج:',
                'type' => 'textarea',
                'group' => 'whatsApp',
                'label' => 'WhatsApp Product Message',
                'description' => 'Default message sent with the product link when ordering via WhatsApp.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'whatsapp_order_message',
                'value' => "*ORDER #{order_number}*\n\n*Total:* {total}\n\n*Items:*\n{items}\n\n🔗 View Order: {order_link}",
                'type' => 'textarea',
                'group' => 'whatsApp',
                'label' => 'WhatsApp Order Message',
                'description' => 'Order message sent via WhatsApp. You can use placeholders: {order_number}, {total}, {items}, {order_link}.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'checkout_alert_message',
                'value' => 'Prices may vary depending on customization, delivery, and other factors. Please contact us for final confirmation.',
                'type' => 'textarea',
                'group' => 'checkout',
                'label' => 'Checkout Alert Message',
                'description' => 'General yellow alert message displayed on the checkout page.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'show_checkout_alert_message',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'checkout',
                'label' => 'Show Checkout Alert Message',
                'description' => 'Enable or disable the yellow alert message on the checkout page.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'checkout_disclaimer_message',
                'value' => 'Prices shown may not always be updated in real-time. The store is not responsible for any discrepancies; please confirm with the merchant before purchase.',
                'type' => 'textarea',
                'group' => 'checkout',
                'label' => 'Checkout Disclaimer Message',
                'description' => 'Red warning message displayed on checkout if prices are not accurate or updated.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'show_checkout_disclaimer_message',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'checkout',
                'label' => 'Show Checkout Disclaimer Message',
                'description' => 'Enable or disable the red warning message on the checkout page.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 7,
            ],

            // Order Settings
            [
                'key' => 'currency',
                'value' => 'EGP',
                'type' => 'text',
                'group' => 'order',
                'label' => 'Default Currency',
                'description' => 'Default currency code used for orders and product prices (e.g., EGP, USD).',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'tax_rate',
                'value' => '0.15',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Tax Rate',
                'description' => 'Default tax rate as a decimal. Example: 0.15 means 15% tax.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'shipping_rate',
                'value' => '0.10',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Shipping Rate',
                'description' => 'Default shipping rate as a decimal. Example: 0.10 means 10%.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'min_shipping_cost',
                'value' => '5',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Minimum Shipping Cost',
                'description' => 'The minimum amount charged for shipping in the default currency.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'max_shipping_cost',
                'value' => '50',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Maximum Shipping Cost',
                'description' => 'The maximum amount charged for shipping in the default currency.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],

            // Social Media Links
            [
                'key' => 'facebook_url',
                'value' => 'https://www.facebook.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Facebook URL',
                'description' => 'Link to your official Facebook page.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Twitter URL',
                'description' => 'Link to your official Twitter profile.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://www.instagram.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Instagram URL',
                'description' => 'Link to your official Instagram profile.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'youtube_url',
                'value' => 'https://www.youtube.com/channel/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'YouTube URL',
                'description' => 'Link to your official YouTube channel.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 7,
            ],
            [
                'key' => 'tiktok_url',
                'value' => 'https://www.tiktok.com/@example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'TikTok URL',
                'description' => 'Link to your official TikTok profile.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 8,
            ],

            // Appearance
            [
                'key' => 'logo_url',
                'value' => '/images/default-logo.webp',
                'type' => 'image',
                'group' => 'appearance',
                'label' => 'Logo URL',
                'description' => 'Path or link to the website logo image.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],

            // About Settings
            [
                'key' => 'who_we_are',
                'value' => 'We are a leading e-commerce store committed to providing quality products and excellent customer service. Our goal is to make your shopping experience simple, enjoyable, and secure.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Who We Are',
                'description' => 'A short introduction about your business, shown in the About Us section.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'our_story',
                'value' => 'Our journey started with a simple idea: to bring quality products closer to everyone, making online shopping accessible and trustworthy.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Our Story',
                'description' => 'Tell the story of how your business started and evolved.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'our_commitment',
                'value' => 'We are committed to offering only the best quality, excellent customer support, and continuous improvement in everything we do.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Our Commitment',
                'description' => 'Explain your mission, values, and customer commitment.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'why_choose_us',
                'value' => 'We provide high-quality products, fast shipping, and dedicated customer service to ensure your satisfaction.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Why Choose Us',
                'description' => 'Highlight the main reasons why customers should choose your business over competitors.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'about_image',
                'value' => '/images/about-default.webp',
                'type' => 'image',
                'group' => 'about',
                'label' => 'About Image',
                'description' => 'Image displayed in the About Us section of the website.',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],

            // Payment Settings
            [
                'key' => 'currency',
                'value' => 'EGP',
                'type' => 'select',
                'group' => 'payment',
                'label' => 'Currency',
                'description' => 'Default currency used for all store payments and transactions.',
                'options' => [
                    ['value' => 'USD', 'label' => 'US Dollar (USD)'],
                    ['value' => 'EUR', 'label' => 'Euro (EUR)'],
                    ['value' => 'GBP', 'label' => 'British Pound (GBP)'],
                    ['value' => 'EGP', 'label' => 'Egyptian Pound (EGP)'],
                ],
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
