<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'value' => 'E-Commerce Store',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Site Name',
                'description' => 'The name of your website displayed in the header and title',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'site_description',
                'value' => 'Your one-stop shop for quality products',
                'type' => 'textarea',
                'group' => 'general',
                'label' => 'Site Description',
                'description' => 'Brief description of your website for SEO and social sharing',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'address',
                'value' => 'EGYPT, Alexandria, al-Ajami',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Address',
                'description' => 'Physical address of the store',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'business_hours',
                'value' => 'Mon-Fri: 9am-5pm',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Business Hours',
                'description' => 'Business hours for the store',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            // contact settings
            [
                'key' => 'contact_email',
                'value' => 'contact@example.com',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Contact Email',
                'description' => 'Primary contact email address',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+1 (234) 567-8900',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Contact Phone',
                'description' => 'Primary contact phone number',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'whatsapp_number',
                'value' => '+1 (234) 567-8900',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'WhatsApp Number',
                'description' => 'WhatsApp number for customer support',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            // Order Settings
            [
                'key' => 'currency',
                'value' => 'EGP',
                'type' => 'text',
                'group' => 'order',
                'label' => 'Default Currency',
                'description' => 'Default currency for orders and prices',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'tax_rate',
                'value' => '0.15',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Tax Rate',
                'description' => 'Default tax rate as a decimal (e.g., 0.15 for 15%)',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'shipping_rate',
                'value' => '0.10',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Shipping Rate',
                'description' => 'Default shipping rate as a decimal (e.g., 0.10 for 10%)',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'min_shipping_cost',
                'value' => '5',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Minimum Shipping Cost',
                'description' => 'Minimum shipping cost in the default currency',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'max_shipping_cost',
                'value' => '50',
                'type' => 'number',
                'group' => 'order',
                'label' => 'Maximum Shipping Cost',
                'description' => 'Maximum shipping cost in the default currency',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'facebook_url',
                'value' => 'https://www.facebook.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Facebook URL',
                'description' => 'URL to your Facebook page',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Twitter URL',
                'description' => 'URL to your Twitter page',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://www.instagram.com/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Instagram URL',
                'description' => 'URL to your Instagram page',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'youtube_url',
                'value' => 'https://www.youtube.com/channel/example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'YouTube URL',
                'description' => 'URL to your YouTube channel',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 7,
            ],
            [
                'key' => 'tiktok_url',
                'value' => 'https://www.tiktok.com/@example',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'TikTok URL',
                'description' => 'URL to your TikTok profile',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 8,
            ],
            [
                'key' => 'logo_url',
                'value' => '/images/default-logo.webp',
                'type' => 'image',
                'group' => 'appearance',
                'label' => 'Logo URL',
                'description' => 'URL to your site logo',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],

            // About Settings
            [
                'key' => 'who_we_are',
                'value' => 'We are a leading e-commerce store committed to providing quality products and excellent customer service. Our goal is to make your shopping experience simple, enjoyable, and secure.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Who We Are',
                'description' => 'A short paragraph describing your business, shown in About Us section',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'our_story',
                'value' => 'Our journey started with a simple idea: to bring quality products closer to everyone, making online shopping accessible and trustworthy.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Our Story',
                'description' => 'Tell the story of how your business started',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'our_commitment',
                'value' => 'We are committed to offering only the best quality, excellent customer support, and continuous improvement in everything we do.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Our Commitment',
                'description' => 'Describe your company’s mission and commitments',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'why_choose_us',
                'value' => 'We provide high-quality products, fast shipping, and dedicated customer service to ensure your satisfaction.',
                'type' => 'textarea',
                'group' => 'about',
                'label' => 'Why Choose Us',
                'description' => 'Explain why customers should choose your business over competitors',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'about_image',
                'value' => '/images/about-default.webp',
                'type' => 'image',
                'group' => 'about',
                'label' => 'About Image',
                'description' => 'Image displayed in the About Us section',
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 5,
            ],

            // Payment Settings
            [
                'key' => 'currency',
                'value' => 'EGP',
                'type' => 'select',
                'group' => 'payment',
                'label' => 'Currency',
                'description' => 'Default currency for the store',
                'options' => [
                    ['value' => 'USD', 'label' => 'US Dollar (USD)'],
                    ['value' => 'EUR', 'label' => 'Euro (EUR)'],
                    ['value' => 'GBP', 'label' => 'British Pound (GBP)'],
                    ['value' => 'EGP', 'label' => 'Egyptian Pound (EGP)'],
                ],
                'is_public' => true,
                'is_protected' => true,
                'sort_order' => 1,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
