<?php

namespace App\Notifications;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Support\Facades\Log;

class CustomResetPassword extends ResetPassword implements ShouldQueue
{
    use Queueable;

    /**
     * Build the mail representation of the notification.
     */
    public function toMail($notifiable)
    {
        // Original reset URL generated by Laravel
        $originalUrl = url(route('reset-password', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));

        // Parse the original URL to extract query parameters
        $parsed = parse_url($originalUrl);
        parse_str($parsed['query'] ?? '', $query);

        $token = $query['token'] ?? null;
        $email = $query['email'] ?? null;

        if (!$token || !$email) {
            Log::error("Missing token or email in password reset URL for user: {$notifiable->id}");
            throw new \Exception('Invalid password reset link generation.');
        }

        // Frontend URL where user will reset password
        $frontendUrl = config('app.frontend_url', 'https://online-shop.cbatu.com');
        $resetRoute = "/auth/reset-password";

        // Final URL with token and email as query params
        $finalUrl = "{$frontendUrl}{$resetRoute}?token={$token}&email=" . urlencode($email);

        // Fetch dynamic settings
        $siteName = \App\Models\Setting::get('site_name', 'E-Commerce Store');
        $logoUrl = \App\Models\Setting::get('logo_url', asset('assets/image/brand/logo.png'));
        $supportEmail = \App\Models\Setting::get('contact_email', 'support@example.com');

        return (new MailMessage)
            ->subject("Reset Your Password - {$siteName}")
            ->markdown('emails.reset-password', [
                'resetUrl' => $finalUrl,
                'user' => $notifiable,
                'siteName' => $siteName,
                'logoUrl' => $logoUrl,
                'supportEmail' => $supportEmail,
            ]);
    }
}
